import { mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, relative } from "node:path";

const require = createRequire(import.meta.url);

export interface GenerateEntryOptions {
  outFile: string;
  userEntryPath: string;
}

export function generateEntry({ outFile, userEntryPath }: GenerateEntryOptions): void {
  mkdirSync(dirname(outFile), { recursive: true });
  const importSpecifier = toImportSpecifier(outFile, userEntryPath);
  // The generated entry lives under the app, so resolve its renderer from the SDK that owns it.
  const reactDomClientSpecifier = require.resolve("react-dom/client");
  const source = `// Auto-generated by rome (rome-app-web). Do not edit.
import { StrictMode } from "react";
import { createRoot, type Root } from ${JSON.stringify(reactDomClientSpecifier)};
import {
  getBootstrap,
  getRegisteredComponent,
  setMountContainer,
  type AppComponentContext,
  type RomeAppBootstrap,
} from "@rome-os/app-web-sdk";
// Imported for side effects too: any top-level defineComponent() calls in the
// app's web entry run on import, populating the SDK registry below.
import UserApp from ${JSON.stringify(importSpecifier)};

let root: Root | null = null;

export async function mount(
  container: HTMLElement,
  bootstrap?: RomeAppBootstrap,
): Promise<void> {
  const resolved = bootstrap ?? getBootstrap();
  setMountContainer(container);
  root = createRoot(container);
  root.render(
    <StrictMode>
      <UserApp bootstrap={resolved} />
    </StrictMode>,
  );
}

export async function unmount(): Promise<void> {
  root?.unmount();
  root = null;
  setMountContainer(null);
}

// Inline app components: the host mounts a single named component (declared in
// app.yaml) into a chat-row shadow root, separate from the full-page mount()
// above. The registry lives in this bundle's copy of the SDK — the same one the
// app's defineComponent() calls wrote to — so the lookup resolves in-process.
const componentCleanups = new WeakMap<HTMLElement, () => void>();

export async function mountComponent(
  container: HTMLElement,
  componentId: string,
  ctx: AppComponentContext,
): Promise<void> {
  const renderer = getRegisteredComponent(componentId);
  if (!renderer) {
    throw new Error(\`App did not register an inline component "\${componentId}"\`);
  }
  const cleanup = await renderer(container, ctx);
  if (typeof cleanup === "function") componentCleanups.set(container, cleanup);
}

export async function unmountComponent(container: HTMLElement): Promise<void> {
  const cleanup = componentCleanups.get(container);
  if (cleanup) {
    cleanup();
    componentCleanups.delete(container);
  }
}
`;
  writeFileSync(outFile, source, "utf8");
}

function toImportSpecifier(fromFile: string, target: string): string {
  let rel = relative(dirname(fromFile), target).replace(/\\/g, "/");
  if (!rel.startsWith(".")) {
    rel = `./${rel}`;
  }
  return rel;
}
