/**
 * Runs Vale over `docs/` and over the comments in `.ts` and `.tsx` sources, and
 * holds the result against a baseline, so the rules in
 * `docs/authoring/WRITING.md` gate new prose without a one-shot rewrite of
 * everything that predates them.
 *
 * Vale itself decides what counts as a violation — the rules live in
 * `.vale/styles/Rome`, not here. This script owns only the verdict: which
 * violations are already known, and whether the diff added any.
 *
 * The comparison is per file and per rule, by count. A line number would move
 * under any edit above it, and the matched text collapses to ";" for the rule
 * that fires most, so neither survives as a key. A count does move when the
 * prose does, in both directions: a new violation raises it and fails, and a
 * fixed one lowers it and also fails, which is what keeps the baseline from
 * outliving the debt.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { BASELINE } from "./prose-baseline.mjs";

export const repoRoot = join(import.meta.dirname, "..");

/**
 * One pass per format, because Vale matches a section by file name rather than
 * by path. A single pass over the source trees would put `[*.md]` — the full
 * docs rule set — onto every package README and Markdown test fixture under
 * them. The glob keeps each pass to the files its rules were written for.
 */
export const PASSES = [
  { glob: "*.md", targets: ["docs"] },
  { glob: "*.{ts,tsx}", targets: ["packages", "rome_apps"] },
];

/** Vale exits 1 when it reports alerts, which is a normal outcome here. */
export function runVale(passes = PASSES, root = repoRoot) {
  const merged = {};
  for (const { glob, targets } of passes) {
    let stdout;
    try {
      stdout = execFileSync("vale", ["--output=JSON", "--no-exit", `--glob=${glob}`, ...targets], {
        cwd: root,
        encoding: "utf8",
        maxBuffer: 64 * 1024 * 1024,
      });
    } catch (error) {
      if (error.code === "ENOENT") {
        throw new Error(
          "vale not found on PATH. Run `nix develop` for the host toolchain — see flake.nix.",
        );
      }
      throw error;
    }
    for (const [file, alerts] of Object.entries(JSON.parse(stdout))) {
      merged[file] = [...(merged[file] ?? []), ...alerts];
    }
  }
  return merged;
}

/** `{ "docs/a.md": { "Rome.Semicolons": 3 } }`, skipping levels below error. */
export function tally(valeReport) {
  const counts = {};
  for (const [file, alerts] of Object.entries(valeReport)) {
    for (const alert of alerts) {
      if (alert.Severity !== "error") continue;
      counts[file] ??= {};
      counts[file][alert.Check] = (counts[file][alert.Check] ?? 0) + 1;
    }
  }
  return counts;
}

/**
 * `added` is prose to fix. `fixed` is a baseline entry to delete, reported as a
 * failure too so the list shrinks by an edit a reviewer sees.
 */
export function diffAgainstBaseline(counts, baseline = BASELINE) {
  const added = [];
  const fixed = [];
  const files = new Set([...Object.keys(counts), ...Object.keys(baseline)]);

  for (const file of [...files].sort()) {
    const now = counts[file] ?? {};
    const before = baseline[file] ?? {};
    const rules = new Set([...Object.keys(now), ...Object.keys(before)]);

    for (const rule of [...rules].sort()) {
      const nowCount = now[rule] ?? 0;
      const beforeCount = before[rule] ?? 0;
      if (nowCount > beforeCount) added.push({ file, rule, nowCount, beforeCount });
      if (nowCount < beforeCount) fixed.push({ file, rule, nowCount, beforeCount });
    }
  }
  return { added, fixed };
}

/** The baseline module, regenerated by `--write`. */
export function renderBaseline(counts) {
  const body = Object.keys(counts)
    .sort()
    .map((file) => {
      const rules = Object.keys(counts[file])
        .sort()
        .map((rule) => `    "${rule}": ${counts[file][rule]},`)
        .join("\n");
      return `  "${file}": {\n${rules}\n  },`;
    })
    .join("\n");

  // `{}` rather than a brace pair around a blank line, so an empty baseline is
  // what the formatter would have written.
  const literal = body ? `{\n${body}\n}` : "{}";

  return `/**
 * Prose predating the gate in \`check-prose.mjs\`, counted per file and per
 * rule. A quarantine list, not an exception list: nothing here is blessed.
 *
 * Empty is the goal state, and the repo is there. An entry earns its place
 * only when a doc cannot be fixed in the change that trips the gate.
 *
 * Regenerate with \`pnpm lint:prose --write\` after fixing prose, and let the
 * diff show the counts falling. A count that only ever rises is the gate
 * working — new prose follows \`docs/authoring/WRITING.md\` from the start.
 */
export const BASELINE = ${literal};
`;
}

function main() {
  const write = process.argv.includes("--write");

  let counts;
  try {
    counts = tally(runVale());
  } catch (error) {
    // A missing binary is a setup mistake, and the fix is one line of prose. A
    // stack trace buries it.
    console.error(error.message);
    process.exit(1);
  }

  if (write) {
    const path = join(repoRoot, "scripts", "prose-baseline.mjs");
    writeFileSync(path, renderBaseline(counts));
    const total = Object.values(counts).reduce(
      (sum, rules) => sum + Object.values(rules).reduce((a, b) => a + b, 0),
      0,
    );
    console.log(`Wrote baseline: ${total} violations across ${Object.keys(counts).length} files.`);
    return;
  }

  const { added, fixed } = diffAgainstBaseline(counts);

  for (const { file, rule, nowCount, beforeCount } of added) {
    console.error(`${file}: ${rule} ${beforeCount} → ${nowCount}. Fix the new prose.`);
  }
  for (const { file, rule, nowCount, beforeCount } of fixed) {
    console.error(
      `${file}: ${rule} ${beforeCount} → ${nowCount}. Run \`pnpm lint:prose --write\`.`,
    );
  }

  if (added.length || fixed.length) {
    console.error("\nRun `vale docs` or `vale <path>` to see the alerts themselves.");
    process.exit(1);
  }
  console.log("Prose matches the baseline.");
}

if (process.argv[1] === new URL(import.meta.url).pathname) main();
